services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres_container
    environment:
      POSTGRES_USER: usr1
      POSTGRES_PASSWORD: pantatining-forminsting-humplionicaned
      POSTGRES_DB: ses
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: what@user.com
      PGADMIN_DEFAULT_PASSWORD: pantatining-forminsting-humplionicaned
    ports:
      - "8081:80"
    depends_on:
      - postgres

  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "80:5173"

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
        - pgbackups:/backups
    links:
        - postgres
    depends_on:
        - postgres
    environment:
        - POSTGRES_HOST=postgres
        - POSTGRES_DB=ses
        - POSTGRES_USER=usr1
        - POSTGRES_PASSWORD=pantatining-forminsting-humplionicaned
        - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
        - SCHEDULE=@every 10m
        - BACKUP_KEEP_DAYS=7
        - BACKUP_KEEP_WEEKS=4
        - BACKUP_KEEP_MONTHS=6
        - BACKUP_KEEP_MINS=5760
        - HEALTHCHECK_PORT=8080


volumes:
  pgdata:
  pgbackups:
